### PR TITLE
fix: check supported network version

### LINKED ISSUE #1036: Add check on add network for checking supported version
As reported here: #1004, we currently don't query the url before adding when the request to add a new network comes via SDK.

To avoid this we should add a new check that queries the version of the network and if not supported returns a error also when adding via SDK.

### PR DESCRIPTION
**Pull request by matt-user**
closes #1036

### CODE REVIEW

File: packages/app/src/systems/Network/services/network.ts [hunk 1]
```diff
@@ -148,11 +149,22 @@ export class NetworkService {
...
+    try {
+      const provider = await Provider.create(url);
+      nodeInfo = await provider.fetchNode();
+    } catch (err: unknown) {
+      throw new Error('Node version is not compatible with the wallet.');
+    }
+    const nodeVersion = parseInt(nodeInfo.nodeVersion.replace('.', ''));
+    if (nodeVersion < MIN_NODE_VERSION) {
+      throw new Error('Node version is not compatible with the wallet.');
+    }
```
Comment (luizstacio) [inline packages/app/src/systems/Network/services/network.ts:167]: We can use `compare-versions` to compare here, them we can have only the string on the config also, `0.22.0`.

**Review by luizstacio — CHANGES_REQUESTED** [review]

File: packages/app/src/systems/Network/services/network.ts [hunk 2]
```diff
@@ -148,11 +150,21 @@ export class NetworkService {
...
     const { name, url } = input.data;
     if (!isValidNetworkUrl(url)) {
       throw new Error('Invalid network URL');
     }
+    let nodeInfo;
+    try {
+      const provider = await Provider.create(url);
+      nodeInfo = await provider.fetchNode();
+    } catch (err: unknown) {
+      throw new Error('Node version is not compatible with the wallet.');
```
Comment (luizstacio) [inline packages/app/src/systems/Network/services/network.ts:163]:
```suggestion
      throw new Error(`Network version is not compatible with >=${MIN_NODE_VERSION} required by the Wallet`);
```

**Review by luizstacio — APPROVED** [review]
