### PR TITLE
fix: nft list getting cut off

### LINKED ISSUE #1779: Add loading state to NFT tab
the new NFT tab doesn't have a loading state

this issue aims to apply exaclty the same logic that we have in the "Assets" tab, but for the NFT one

### PR DESCRIPTION
**Pull request by arthurgeron**
- Closes #1779 
- Closes FE-1328

# Summary
- Added a general loading state for the entire NFT list for when the account data is still loading
- Fixed NFT image collapsible loading state not matching the sizes of NFT images later displayed
- Fixed NFT Image list getting cut off

# Checklist

- [x] I've added error handling for all actions/requests, and verified how this error will show on UI. (or there was no error handling)
- [x] I've reviewed all the copy changed/added in this PR, using AI if needed. (or there was no copy changes)
- [x] I've included the reference to the issues being closed from Github and/or Linear (or there was no issues)
- [x] I've changed the Docs to reflect my changes (or it was not needed)
- [x] I've put docs links where it may be helpful (or it was not needed)
- [x] I checked the resulting UI both in Light and Dark mode (or no UI changes were made)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)

### CODE REVIEW

File: packages/app/src/systems/Account/components/BalanceNFTs/NFTImage.tsx [hunk 1]
```diff
@@ -25,31 +34,22 @@ export const NFTImage = ({ assetId, image }: NFTImageProps) => {
...
+  return (
+    <Box css={styles.item}>
+      {image && !fallback && isLoading && <NFTImageLoading />}
+      {image && !fallback && (
+        <Image
           ref={imgRef}
           src={image}
           alt={shortAddress(assetId)}
           data-loading={isLoading}
+          style={cssObj({ visibility: isLoading ? 'hidden' : 'visible' })}
```
Comment (helciofranco) [inline packages/app/src/systems/Account/components/BalanceNFTs/NFTImage.tsx:48]: I added a data-attribute for that
take a look here:

```tsx
'img[data-loading="true"]': {
      display: 'none',
 },
```

this condition is conflicting with the styles

I'd keep your logics but updating the css on that selector below

**Comment by LuizAsFight** [comment]
needs to fix on NFT tab loading 
image

File: packages/app/src/systems/Account/components/BalanceNFTs/NFTImage.tsx (hunk 1 above)
Comment (arthurgeron) [reply packages/app/src/systems/Account/components/BalanceNFTs/NFTImage.tsx:48]: Fixed, thanks

Comment (helciofranco) [reply packages/app/src/systems/Account/components/BalanceNFTs/NFTImage.tsx:48]: I think @LuizAsFight override your commit lol
